export const products = [
  {
    name: "Dell Inspiron 15 example for testing line camp and other title features djfdkfjdkfjdkjfkdjf kjj kj kj kjkjkvk kjfvdfkjvdjujndrfv fkjdfvin ldknfvbidjfv dklfvlkdjf hello",
    price: 699990,
    discount: 10,
    image: "https://unsplash.com/photos/m_HRfLhgABo/download",
    description: "A powerful and reliable laptop for everyday computing needs.",
  },
  {
    name: "Apple iPhone 13",
    price: 999990,
    discount: false,
    image: "https://unsplash.com/photos/m_HRfLhgABo/download",
    description:
      "Latest iPhone model with advanced features and great performance.",
  },
  {
    name: "Sony WH-1000XM4 Headphones",
    price: 299990,
    discount: 2,
    image: "https://unsplash.com/photos/m_HRfLhgABo/download",
    description: "High-quality noise-canceling headphones for immersive sound.",
  },
  {
    name: "Samsung Galaxy S21",
    price: 799990,
    discount: false,
    image: "https://unsplash.com/photos/vS24aE0ZgK8/download",
    description: "Samsung's flagship smartphone with excellent camera quality.",
  },
  {
    name: "Apple MacBook Pro",
    price: 1299990,
    discount: 14,
    image: "https://unsplash.com/photos/m_HRfLhgABo/download",
    description: "Powerful laptop designed for professionals.",
  },
  {
    name: "Microsoft Surface Pro 7",
    price: 749990,
    discount: 15,
    image: "https://unsplash.com/photos/YFtxBZmg31g/download",
    description: "Versatile 2-in-1 tablet with laptop-grade performance.",
  },
  {
    name: "JBL Flip 5 Speaker",
    price: 99990,
    discount: 11,
    image: "https://unsplash.com/photos/tMlAXdcIV3Y/download",
    description: "Portable waterproof Bluetooth speaker with powerful sound.",
  },
  {
    name: "Canon EOS 5D Mark IV",
    price: 2499990,
    discount: 12,
    image: "https://unsplash.com/photos/hGV2TfOh0ns/download",
    description: "High-performance DSLR camera for professional photographers.",
  },
  {
    name: "Beats by Dre Studio3",
    price: 349990,
    discount: 16,
    image: "https://unsplash.com/photos/FPkJq_pF0sU/download",
    description: "Wireless noise-canceling headphones with a sleek design.",
  },
  {
    name: "Nintendo Switch",
    price: 299990,
    discount: 17,
    image: "https://unsplash.com/photos/RaX5voHdB6k/download",
    description: "Versatile gaming console for at-home and portable play.",
  },
  {
    name: "Bose SoundLink Revolve",
    price: 199990,
    discount: 13,
    image: "https://unsplash.com/photos/1zH7JjwvZZE/download",
    description: "Compact, high-quality Bluetooth speaker with deep sound.",
  },
  {
    name: "Amazon Kindle Paperwhite",
    price: 129990,
    discount: 13,
    image: "https://unsplash.com/photos/XKbtSa5gmu8/download",
    description: "Lightweight e-reader with high-resolution display.",
  },
  {
    name: "HP Pavilion 15",
    price: 649990,
    discount: 10,
    image: "https://unsplash.com/photos/VtKoSy_XzNU/download",
    description: "Affordable and versatile laptop with excellent performance.",
  },
  {
    name: "Roku Streaming Stick+",
    price: 49990,
    discount: 10,
    image: "https://unsplash.com/photos/nmTm7knUnqs/download",
    description: "Easy-to-use streaming device with HD and 4K support.",
  },
  {
    name: "Samsung Galaxy Tab S7",
    price: 499990,
    discount: 10,
    image: "https://unsplash.com/photos/8-lRFSHUpjs/download",
    description: "High-performance tablet for productivity and entertainment.",
  },
  {
    name: "Google Nest Thermostat",
    price: 129990,
    discount: 10,
    image: "https://unsplash.com/photos/TxXuhHIlZuQ/download",
    description: "Smart thermostat with energy-saving features.",
  },
  {
    name: "Sony PlayStation 5",
    price: 499990,
    discount: 10,
    image: "https://unsplash.com/photos/NntcGf2lIuw/download",
    description: "Next-generation gaming console with advanced graphics.",
  },
  {
    name: "Anker PowerCore 10000",
    price: 25990,
    discount: 10,
    image: "https://unsplash.com/photos/tLZGJ29DOuI/download",
    description: "Compact portable charger with high-speed charging.",
  },
  {
    name: "DJI Mini 2 Drone",
    price: 449990,
    discount: 10,
    image: "https://unsplash.com/photos/Qj6XJK8qEoA/download",
    description: "Lightweight, portable drone with 4K video capability.",
  },
  {
    name: "Logitech MX Master 3",
    price: 99990,
    discount: 10,
    image: "https://unsplash.com/photos/A_j_yI40CbM/download",
    description: "High-precision wireless mouse with ergonomic design.",
  },
];
